defaults:
  url: https://packages.tq-group.com/energymanager/apps/{app}/{name}_{version}_{arch}.empkg
  cache: true

apps:
  button-handler:
    version: '3.0.7'

  data-transfer:
    version: '4.1.2'

  device-settings:
    version: '5.0.6'

  flash-scan:
    version: '2.2.9'

  health-check:
    version: '3.0.1'

  teridiand:
    version: '1.11.3'

  teridiand-fw:
    arch: 'all'
    version: '1.3.6'

  ui-container:
    arch: 'all'
    version: '1.2.2'

  updater:
    version: '2.0.7'

  web-login:
    version: '3.2.1'
